### ISSUE TITLE
Teensy 3.6 (kint36) advanced QMK features umbrella bug

### ISSUE THREAD

**Issue by stapelberg** [kinx-project/kint#10]
The following features are either known to not work, or have not yet been successfully tested yet:

* [x] EEPROM, for persistent settings
* [ ] [Audio](https://beta.docs.qmk.fm/using-qmk/hardware-features/feature_audio)
* [x] [RGB LED lighting](https://beta.docs.qmk.fm/using-qmk/hardware-features/lighting/feature_rgblight)

**Comment by ameyp** [comment]
I've got RGB LED lighting working with this:

```
#define STM32_SYSCLK KINETIS_SYSCLK_FREQUENCY
#define NOP_FUDGE 0.4
#define RGB_DI_PIN LINE_PIN28
```

**Comment by stapelberg** [comment]
> I've got RGB LED lighting working with this:

Thank you, @ameyp, I can confirm that RGB LED works for me, too!

I have filed https://github.com/kinx-project/kint/issues/36 for the audio support and will close this umbrella bug.
